;; Anki flashcard queue - DO NOT EDIT MANUALLY
;; This file is auto-generated by Emacs

(setq anki-flashcard-queue
  '(
    "20240929173550-komutativna_algebra.org"
    "20240929173550-riemannove_ploskve.org"
  ))
