;; Anki flashcard queue - DO NOT EDIT MANUALLY
;; This file is auto-generated by Emacs

(setq anki-flashcard-queue
  '(
    "20220324201721-integral_domain.org"
    "20251001233047-nekomutativna_algebra.org"
    "2025-08-07.org"
    "journals/2025-08-07.org"
    "20240929173550-komutativna_algebra.org"
    "20240929173550-riemannove_ploskve.org"
  ))
